// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type CommonResponse struct {
	Message string `json:"message"`
}

type RegisterBaseInfo struct {
	UserName string `json:"userName"`
	PassWord string `json:"pw"`
	Role     int    `json:"role"`
}

type RegisterInfo struct {
	RegisterBaseInfo
	SchoolNum  string `json:"sNo"`
	SchoolName string `json:"sName"`
	Grade      int    `json:"grade"`
}
