// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"schoolLifeDemo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: SchoolLifeDemoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/school/codemap",
				Handler: SchoolCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/orders",
				Handler: UserOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/schoolwal/noteslist",
				Handler: NotesListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/userInfo",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schoolwall/sentnotes",
				Handler: SendNotesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schoolwall/imgUpload",
				Handler: ImgUploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
